baseURL: "https://fredrikaverpil.github.io"
languageCode: en-us
title: Fredrik Averpil
theme: PaperMod
enableGitInfo: true

frontmatter:
  date:
    - date
    - created
  lastmod:
    - lastmod
    - updated
    - ":git"
    - date
    - ":fileModTime"
menu:
  main:
    - name: about
      url: /
      weight: 1
    - name: blog
      url: /posts/
      weight: 2
    - name: cheat-sheets
      url: /cheat-sheets/
      weight: 3
    - name: search
      url: /search/
      weight: 4
    - name: tags
      url: /tags/
      weight: 5
taxonomies:
  tag: tags
markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    # guessSyntax: true
    lineNos: true # messes up background color
    # noClasses: false
    style: dracula
params:
  defaultTheme: dark
  disableThemeToggle: false
  assets:
    disableHLJS: true # enables markup.highlight..
  profileMode:
    enabled: true
    # title: "Hey there 👋" # optional default will be site title
    subtitle: "Software engineer ❤️ [Python](http://python.org/)"
    imageUrl: "static/memoji.png" # optional
    # imageTitle: "<title of image as alt>" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    # buttons:
    #   - name: Archive
    #     url: "/archive"
    #   - name: Github
    #     url: "https://github.com/"
  socialIcons: # optional
    - name: "GitHub"
      url: "https://github.com/fredrikaverpil"
    - name: "Mastodon"
      url: "https://fosstodon.org/web/@fredrikaverpil"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/fredrik/"
    - name: "RSS"
      url: "index.xml"

  editPost:
    URL: "https://github.com/fredrikaverpil/fredrikaverpil.github.io/tree/main/obsidian/"
    Text: "Suggest Changes"
    appendFilePath: true
  ShowPostNavLinks: true
  ShowReadingTime: true
  ShowCodeCopyButtons: true

  # PaperModX
  TocSide: "right"

assets:
  favicon: "/static/favicon.ico"
  # theme_color: "#24242e"

outputs:
  home:
    - HTML
    - RSS
    - JSON
module:
  mounts:
    - source: "static"
      target: "static/static"
