version: 2

updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"

registries:
  github:
    type: git
    url: https://github.com/squidfunk/mkdocs-material-insiders
    username: x-access-token
    password: ${{ secrets.MKDOCS_MATERIAL_INSIDERS }}
