version: 2

updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    registries:
      - mkdocs-material-insiders
    schedule:
      interval: "weekly"

registries:
  mkdocs-material-insiders:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{ secrets.MKDOCS_MATERIAL_INSIDERS }}
