docs_dir: mkdocs
site_dir: site
site_name: Fredrik Averpil
# repo_url: https://github.com/fredrikaverpil/fredrikaverpil.github.io
repo_name: fredrikaverpil.github.io

plugins:
  - search # must be re-added when plugins are specified
  - meta

markdown_extensions:
  # Admonitions
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # Code block syntax highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  # Emojis
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  # Other
  - footnotes
  - tables

theme:
  name: material
  icon:
    logo: bootstrap/terminal-fill
  # font: false # prevent google fonts from loading
  font:
    # text: JetBrains Mono
    code: JetBrains Mono
  favicon: static/favicon.ico
  features:
    - toc.follow
    - search.highlight
    - content.code.copy
    - content.code.annotate
  custom_dir: mkdocs/overrides

extra_css:
  - stylesheets/extra.css

extra:
  generator: false # remove "Made with Material for MkDocs" from footer
  social:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/?h=fontawesome#social-links
    - icon: fontawesome/brands/github
      link: https://github.com/fredrikaverpil
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@fredrikaverpil
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/fredrikaverpil
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/fredrik
    - icon: fontawesome/solid/square-rss
      link: sitemap.xml

nav:
  - Blog:
      - index.md
