docs_dir: mkdocs
site_dir: site
site_name: Fredrik Averpil
site_url: https://fredrikaverpil.github.io
# repo_url: https://github.com/fredrikaverpil/fredrikaverpil.github.io
repo_name: fredrikaverpil.github.io

markdown_extensions:
  - admonition
  - footnotes
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.snippets:
      url_download: true
      check_paths: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  # Emojis
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme:
  name: material
  icon:
    logo: "material/console"
  favicon: static/favicon.ico
  features:
    - toc.follow
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - navigation.tabs
    - navigation.sections
  custom_dir: mkdocs/overrides

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # NOTE: the order of the palettes below matter.
    # The first one in the list will become the default for the user.

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to system preference

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue gray
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fredrikaverpil
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@fredrikaverpil
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/fredrikaverpil.github.io
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/fredrik
    - icon: fontawesome/solid/square-rss
      link: /feed_rss_created.xml
    - icon: simple/feedly
      link: https://feedly.com/i/subscription/feed%2Fhttps%3A%2F%2Ffredrikaverpil.github.io%2Ffeed_rss_created.xml
    - icon: octicons/graph-24
      link: https://analytics.umami.is/share/tJcIgDO3dznRmeGX/fredrikaverpil.github.io
  analytics:
    provider: umami
  # google search console verification, see overrides
  google_site_verification: 'gXcJysapgO5NIymnJqWVQXMp3KtnsJ6_A3zJHLdDuXo'

exclude_docs: |
  !.well-known

plugins:
  # NOTE: all plugins must be defined in one and the same yml file

  # - redirects:
  #     redirect_maps:
  #       "index.md": "blog/index.md"
  - search # must be re-added when plugins are specified
  - tags: # must be defined before the "blog" plugin
      tags_file: tags.md
  # WARNING: comment out social cards before running 'mkdocs build' locally, to avoid cairo issues...
  # - social:
  #     cards: true
  # WARNING: the 'meta' plugin is an insiders-only feature
  # - meta # must be defined before the "blog" plugin
  - blog:
      blog_toc: true
      post_date_format: long
      post_readtime: true
      archive: true
      categories: false
      authors: true
      authors_file: .authors.yml
  - rss:
      match_path: blog/posts/.*
      abstract_chars_count: -1 # include entire post in rss, for rss readers
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
      image: https://github.com/fredrikaverpil.png

nav:
  - Blog:
      - blog/index.md
      - tags.md
  - Cheat sheets:
      - cheat-sheets/docker.md
      - cheat-sheets/gha.md
      - cheat-sheets/git.md
      - cheat-sheets/gcal.md
      - cheat-sheets/remote_play.md
  - About me: index.md
