name: check

on:
  workflow_dispatch:
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          cache: pip
          python-version-file: .python-version

      - run: pip install ruff
      - run: ruff --select=ALL .
